Logging started at 2015-10-28 17:32:13
File name: C:\Users\root\Dropbox\Vencillio Advanced\VA Source\.\data\logs\err\1446049933373 - root - [Wed Oct 28][5.32PM].txt
System.getProperty("os.name"): "Windows Server 2008 R2"

[2015-10-28 17:37:40] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 17:37:40] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 17:37:40] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 17:37:40] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 17:37:40] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 17:37:40] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 17:37:40] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 17:37:40] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 17:37:40] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 17:37:40] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 17:37:40] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 17:37:40] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 17:37:40] java.lang.NullPointerException
[2015-10-28 17:37:40] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 17:37:40] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 17:37:40] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 17:37:40] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 17:37:40] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 17:37:40] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 17:45:43] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 17:45:43] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 17:45:43] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 17:45:43] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 17:45:43] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 17:45:43] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 17:45:43] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 17:45:43] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 17:45:43] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 17:45:43] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 17:45:43] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 17:45:43] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 17:45:43] java.lang.NullPointerException
[2015-10-28 17:45:43] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 17:45:43] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 17:45:43] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 17:45:43] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 17:45:43] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 17:45:43] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 17:58:45] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 17:58:45] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 17:58:45] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 17:58:45] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 17:58:45] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 17:58:45] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 17:58:45] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 17:58:45] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 17:58:45] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 17:58:45] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 17:58:45] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 17:58:45] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 17:58:45] java.lang.NullPointerException
[2015-10-28 17:58:45] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 17:58:45] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 17:58:45] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 17:58:45] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 17:58:45] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 17:58:45] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 18:18:50] java.lang.NumberFormatException: For input string: "2==3000000"
[2015-10-28 18:18:50] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-28 18:18:50] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-28 18:18:50] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-28 18:18:50] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-28 18:18:50] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-28 18:18:50] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-28 18:18:50] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-28 18:18:50] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-28 18:18:50] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-28 18:18:50] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 18:25:45] java.lang.ArrayIndexOutOfBoundsException: 1
[2015-10-28 18:25:45] 	at com.vencillio.rs2.content.skill.mining.Mining$1.execute(Mining.java:272)
[2015-10-28 18:25:45] 	at com.vencillio.core.task.Task.run(Task.java:183)
[2015-10-28 18:25:45] 	at com.vencillio.core.task.TaskQueue.process(TaskQueue.java:78)
[2015-10-28 18:25:45] 	at com.vencillio.core.GameThread.cycle(GameThread.java:116)
[2015-10-28 18:25:45] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 18:26:00] java.lang.ArrayIndexOutOfBoundsException: 1
[2015-10-28 18:26:00] 	at com.vencillio.rs2.content.skill.mining.Mining$1.execute(Mining.java:272)
[2015-10-28 18:26:00] 	at com.vencillio.core.task.Task.run(Task.java:183)
[2015-10-28 18:26:00] 	at com.vencillio.core.task.TaskQueue.process(TaskQueue.java:78)
[2015-10-28 18:26:00] 	at com.vencillio.core.GameThread.cycle(GameThread.java:116)
[2015-10-28 18:26:00] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 18:42:09] java.lang.NullPointerException
[2015-10-28 18:42:09] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2015-10-28 18:42:09] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:115)
[2015-10-28 18:42:09] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-28 18:42:09] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-28 18:42:09] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-28 18:42:09] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-28 18:42:09] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 18:42:20] java.lang.NullPointerException
[2015-10-28 18:42:20] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2015-10-28 18:42:20] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:115)
[2015-10-28 18:42:20] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-28 18:42:20] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-28 18:42:20] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-28 18:42:20] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-28 18:42:20] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 18:53:42] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 18:53:42] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 18:53:42] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 18:53:42] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 18:53:42] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 18:53:42] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 18:53:42] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 18:53:42] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 18:53:42] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 18:53:42] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 18:53:42] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 18:53:42] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 18:53:42] java.lang.NullPointerException
[2015-10-28 18:53:42] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 18:53:42] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 18:53:42] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 18:53:42] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 18:53:42] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 18:53:42] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 19:03:17] java.lang.ArrayIndexOutOfBoundsException: 1
[2015-10-28 19:03:17] 	at com.vencillio.rs2.content.skill.mining.Mining$1.execute(Mining.java:272)
[2015-10-28 19:03:17] 	at com.vencillio.core.task.Task.run(Task.java:183)
[2015-10-28 19:03:17] 	at com.vencillio.core.task.TaskQueue.process(TaskQueue.java:78)
[2015-10-28 19:03:17] 	at com.vencillio.core.GameThread.cycle(GameThread.java:116)
[2015-10-28 19:03:17] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 19:08:27] java.lang.ArrayIndexOutOfBoundsException: 1
[2015-10-28 19:08:27] 	at com.vencillio.rs2.content.skill.mining.Mining$1.execute(Mining.java:272)
[2015-10-28 19:08:27] 	at com.vencillio.core.task.Task.run(Task.java:183)
[2015-10-28 19:08:27] 	at com.vencillio.core.task.TaskQueue.process(TaskQueue.java:78)
[2015-10-28 19:08:27] 	at com.vencillio.core.GameThread.cycle(GameThread.java:116)
[2015-10-28 19:08:27] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 19:22:23] java.lang.NumberFormatException: For input string: "7.5000000"
[2015-10-28 19:22:23] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-28 19:22:23] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-28 19:22:23] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-28 19:22:23] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-28 19:22:23] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-28 19:22:23] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-28 19:22:23] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-28 19:22:23] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-28 19:22:23] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-28 19:22:23] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 19:42:46] java.lang.ArrayIndexOutOfBoundsException: 1
[2015-10-28 19:42:46] 	at com.vencillio.rs2.content.skill.mining.Mining$1.execute(Mining.java:272)
[2015-10-28 19:42:46] 	at com.vencillio.core.task.Task.run(Task.java:183)
[2015-10-28 19:42:46] 	at com.vencillio.core.task.TaskQueue.process(TaskQueue.java:78)
[2015-10-28 19:42:46] 	at com.vencillio.core.GameThread.cycle(GameThread.java:116)
[2015-10-28 19:42:46] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-28 21:31:24] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 21:31:24] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 21:31:24] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 21:31:24] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 21:31:24] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 21:31:24] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 21:31:24] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 21:31:24] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 21:31:24] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 21:31:24] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 21:31:24] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 21:31:24] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 21:31:24] java.lang.NullPointerException
[2015-10-28 21:31:24] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 21:31:24] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 21:31:24] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 21:31:24] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 21:31:24] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 21:31:24] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 21:32:39] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 21:32:39] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 21:32:39] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 21:32:39] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 21:32:39] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 21:32:39] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 21:32:39] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 21:32:39] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 21:32:39] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 21:32:39] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 21:32:39] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 21:32:39] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 21:32:39] java.lang.NullPointerException
[2015-10-28 21:32:39] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 21:32:39] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 21:32:39] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 21:32:39] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 21:32:39] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 21:32:39] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 21:34:59] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 21:34:59] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 21:34:59] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 21:34:59] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 21:34:59] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 21:34:59] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 21:34:59] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 21:34:59] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 21:34:59] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 21:34:59] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 21:34:59] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 21:34:59] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 21:34:59] java.lang.NullPointerException
[2015-10-28 21:34:59] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 21:34:59] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 21:34:59] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 21:34:59] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 21:34:59] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 21:34:59] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 23:47:52] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-28 23:47:52] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-28 23:47:52] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 23:47:52] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-28 23:47:52] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-28 23:47:52] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-28 23:47:52] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-28 23:47:52] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-28 23:47:52] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 23:47:52] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 23:47:52] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 23:47:52] 	at java.lang.Thread.run(Unknown Source)
[2015-10-28 23:47:52] java.lang.NullPointerException
[2015-10-28 23:47:52] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-28 23:47:52] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-28 23:47:52] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-28 23:47:52] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-28 23:47:52] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-28 23:47:52] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 01:57:48] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 01:57:48] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 01:57:48] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 01:57:48] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 01:57:48] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 01:57:48] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 01:57:48] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 01:57:48] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 01:57:48] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 01:57:48] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 01:57:48] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 01:57:48] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 01:57:48] java.lang.NullPointerException
[2015-10-29 01:57:48] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 01:57:48] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 01:57:48] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 01:57:48] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 01:57:48] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 01:57:48] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 02:52:56] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 02:52:56] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 02:52:56] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 02:52:56] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 02:52:56] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 02:52:56] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 02:52:56] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 02:52:56] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 02:52:56] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 02:52:56] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 02:52:56] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 02:52:56] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 02:52:56] java.lang.NullPointerException
[2015-10-29 02:52:56] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 02:52:56] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 02:52:56] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 02:52:56] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 02:52:56] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 02:52:56] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 02:53:48] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 02:53:48] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 02:53:48] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 02:53:48] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 02:53:48] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 02:53:48] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 02:53:48] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 02:53:48] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 02:53:48] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 02:53:48] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 02:53:48] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 02:53:48] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 02:53:48] java.lang.NullPointerException
[2015-10-29 02:53:48] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 02:53:48] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 02:53:48] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 02:53:48] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 02:53:48] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 02:53:48] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 03:01:21] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 03:01:21] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 03:01:21] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 03:01:21] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 03:01:21] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 03:01:21] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 03:01:21] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 03:01:21] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 03:01:21] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 03:01:21] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 03:01:21] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 03:01:21] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 03:01:21] java.lang.NullPointerException
[2015-10-29 03:01:21] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 03:01:21] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 03:01:21] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 03:01:21] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 03:01:21] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 03:01:21] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 03:04:16] java.lang.NullPointerException
[2015-10-29 03:04:16] 	at com.vencillio.rs2.entity.movement.PlayerMovementHandler.process(PlayerMovementHandler.java:51)
[2015-10-29 03:04:16] 	at com.vencillio.rs2.entity.World.process(World.java:356)
[2015-10-29 03:04:16] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 03:04:16] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 03:20:54] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 03:20:54] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 03:20:54] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 03:20:54] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 03:20:54] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 03:20:54] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 03:20:54] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 03:20:54] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 03:20:54] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 03:20:54] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 03:20:54] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 03:20:54] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 03:20:54] java.lang.NullPointerException
[2015-10-29 03:20:54] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 03:20:54] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 03:20:54] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 03:20:54] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 03:20:54] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 03:20:54] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 03:51:17] java.lang.NumberFormatException: For input string: "100k"
[2015-10-29 03:51:17] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 03:51:17] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 03:51:17] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 03:51:17] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-29 03:51:17] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 03:51:17] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 03:51:17] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 03:51:17] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 03:51:17] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 06:46:24] java.lang.NumberFormatException: For input string: "150k"
[2015-10-29 06:46:24] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 06:46:24] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 06:46:24] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 06:46:24] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-29 06:46:24] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 06:46:24] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 06:46:24] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 06:46:24] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 06:46:24] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 07:33:25] java.lang.NumberFormatException: For input string: "\"
[2015-10-29 07:33:25] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 07:33:25] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 07:33:25] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 07:33:25] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-29 07:33:25] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-29 07:33:25] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 07:33:25] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 07:33:25] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 07:33:25] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 07:33:25] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 07:53:59] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 07:53:59] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 07:53:59] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:53:59] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:53:59] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 07:53:59] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 07:53:59] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 07:53:59] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 07:53:59] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:53:59] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:53:59] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:53:59] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:53:59] java.lang.NullPointerException
[2015-10-29 07:53:59] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 07:53:59] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 07:53:59] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:53:59] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:53:59] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:53:59] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:54:40] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 07:54:40] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 07:54:40] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:54:40] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:54:40] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 07:54:40] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 07:54:40] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 07:54:40] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 07:54:40] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:54:40] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:54:40] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:54:40] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:54:40] java.lang.NullPointerException
[2015-10-29 07:54:40] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 07:54:40] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 07:54:40] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:54:40] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:54:40] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:54:40] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:54:58] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 07:54:58] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-29 07:54:58] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:54:58] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:54:58] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 07:54:58] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 07:54:58] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 07:54:58] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 07:54:58] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:54:58] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:54:58] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:54:58] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:54:58] java.lang.NullPointerException
[2015-10-29 07:54:58] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 07:54:58] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 07:54:58] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:54:58] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:54:58] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:54:58] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:55:29] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 07:55:29] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 07:55:29] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:55:29] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 07:55:29] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 07:55:29] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 07:55:29] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 07:55:29] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:55:29] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:55:29] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:55:29] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:55:29] java.lang.NullPointerException
[2015-10-29 07:55:29] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 07:55:29] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 07:55:29] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:55:29] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:55:29] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:55:29] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:56:50] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 07:56:50] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 07:56:50] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 07:56:50] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 07:56:50] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 07:56:50] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 07:56:50] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 07:56:50] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:56:50] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:56:50] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:56:50] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 07:56:50] java.lang.NullPointerException
[2015-10-29 07:56:50] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 07:56:50] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 07:56:50] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 07:56:50] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 07:56:50] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 07:56:50] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 08:27:27] java.lang.NumberFormatException: For input string: "100k"
[2015-10-29 08:27:27] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 08:27:27] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 08:27:27] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 08:27:27] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-29 08:27:27] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 08:27:27] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 08:27:27] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 08:27:27] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 08:27:27] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 08:49:37] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 08:49:37] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 08:49:37] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 08:49:37] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 08:49:37] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 08:49:37] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 08:49:37] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 08:49:37] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 08:49:37] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 08:49:37] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 08:49:37] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 08:49:37] java.lang.NullPointerException
[2015-10-29 08:49:37] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 08:49:37] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 08:49:37] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 08:49:37] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 08:49:37] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 08:49:37] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 10:32:49] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 10:32:49] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 10:32:49] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 10:32:49] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 10:32:49] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 10:32:49] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 10:32:49] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 10:32:49] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 10:32:49] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 10:32:49] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 10:32:49] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 10:32:49] java.lang.NullPointerException
[2015-10-29 10:32:49] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 10:32:49] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 10:32:49] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 10:32:49] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 10:32:49] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 10:32:49] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 10:42:42] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 10:42:42] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 10:42:42] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 10:42:42] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 10:42:42] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 10:42:42] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 10:42:42] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 10:42:42] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 10:42:42] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 10:42:42] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 10:42:42] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 10:42:42] java.lang.NullPointerException
[2015-10-29 10:42:42] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 10:42:42] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 10:42:42] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 10:42:42] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 10:42:42] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 10:42:42] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 10:44:00] java.lang.NumberFormatException: For input string: "#"
[2015-10-29 10:44:00] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 10:44:00] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 10:44:00] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 10:44:00] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-29 10:44:00] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-29 10:44:00] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 10:44:00] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 10:44:00] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 10:44:00] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 10:44:00] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 11:44:47] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 11:44:47] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 11:44:47] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 11:44:47] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 11:44:47] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 11:44:47] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 11:44:47] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 11:44:47] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 11:44:47] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 11:44:47] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 11:44:47] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 11:44:47] java.lang.NullPointerException
[2015-10-29 11:44:47] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 11:44:47] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 11:44:47] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 11:44:47] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 11:44:47] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 11:44:47] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 11:45:27] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 11:45:27] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 11:45:27] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 11:45:27] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 11:45:27] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 11:45:27] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 11:45:27] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 11:45:27] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 11:45:27] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 11:45:27] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 11:45:27] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 11:45:27] java.lang.NullPointerException
[2015-10-29 11:45:27] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 11:45:27] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 11:45:27] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 11:45:27] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 11:45:27] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 11:45:27] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 11:46:16] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 11:46:16] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 11:46:16] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 11:46:16] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 11:46:16] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 11:46:16] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 11:46:16] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 11:46:16] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 11:46:16] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 11:46:16] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 11:46:16] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 11:46:16] java.lang.NullPointerException
[2015-10-29 11:46:16] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 11:46:16] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 11:46:16] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 11:46:16] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 11:46:16] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 11:46:16] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 12:46:00] java.lang.NumberFormatException: For input string: "50k"
[2015-10-29 12:46:00] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 12:46:00] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 12:46:00] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-29 12:46:00] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-29 12:46:00] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 12:46:00] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 12:46:00] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 12:46:00] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 12:46:00] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 14:14:10] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 14:14:10] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 14:14:10] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 14:14:10] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 14:14:10] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 14:14:10] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 14:14:10] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 14:14:10] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 14:14:10] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 14:14:10] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 14:14:10] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 14:14:10] java.lang.NullPointerException
[2015-10-29 14:14:10] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 14:14:10] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 14:14:10] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 14:14:10] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 14:14:10] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 14:14:10] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 14:59:38] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 14:59:38] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 14:59:38] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 14:59:38] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 14:59:38] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 14:59:38] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 14:59:38] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 14:59:38] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 14:59:38] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 14:59:38] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 14:59:38] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 14:59:38] java.lang.NullPointerException
[2015-10-29 14:59:38] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 14:59:38] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 14:59:38] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 14:59:38] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 14:59:38] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 14:59:38] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 16:50:44] java.lang.NullPointerException
[2015-10-29 16:50:44] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2015-10-29 16:50:44] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:115)
[2015-10-29 16:50:44] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 16:50:44] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 16:50:44] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 16:50:44] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 16:50:44] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 16:51:23] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 16:51:23] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 16:51:23] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 16:51:23] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 16:51:23] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 16:51:23] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 16:51:23] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 16:51:23] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 16:51:23] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 16:51:23] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 16:51:23] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 16:51:23] java.lang.NullPointerException
[2015-10-29 16:51:23] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 16:51:23] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 16:51:23] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 16:51:23] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 16:51:23] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 16:51:23] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 16:56:44] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 16:56:44] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 16:56:44] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 16:56:44] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 16:56:44] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 16:56:44] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 16:56:44] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 16:56:44] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 16:56:44] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 16:56:44] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 16:56:44] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 16:56:44] java.lang.NullPointerException
[2015-10-29 16:56:44] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 16:56:44] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 16:56:44] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 16:56:44] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 16:56:44] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 16:56:44] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 17:53:29] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 17:53:29] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 17:53:29] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 17:53:29] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 17:53:29] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 17:53:29] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 17:53:29] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 17:53:29] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 17:53:29] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 17:53:29] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 17:53:29] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 17:53:29] java.lang.NullPointerException
[2015-10-29 17:53:29] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 17:53:29] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 17:53:29] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 17:53:29] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 17:53:29] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 17:53:29] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 18:22:19] java.lang.NumberFormatException: For input string: "4000i"
[2015-10-29 18:22:19] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 18:22:19] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 18:22:19] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 18:22:19] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-29 18:22:19] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-29 18:22:19] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 18:22:19] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 18:22:19] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 18:22:19] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 18:22:19] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 18:28:38] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 18:28:38] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 18:28:38] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 18:28:38] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 18:28:38] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 18:28:38] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 18:28:38] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 18:28:38] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 18:28:38] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 18:28:38] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 18:28:38] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 18:28:38] java.lang.NullPointerException
[2015-10-29 18:28:38] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 18:28:38] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 18:28:38] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 18:28:38] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 18:28:38] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 18:28:38] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 18:33:24] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'where clause'
[2015-10-29 18:33:24] 	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
[2015-10-29 18:33:24] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-29 18:33:24] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.Util.getInstance(Util.java:381)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-29 18:33:24] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1912)
[2015-10-29 18:33:24] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:224)
[2015-10-29 18:33:24] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-29 18:33:24] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 18:33:24] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 18:33:24] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 18:33:24] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 18:33:24] java.lang.NullPointerException
[2015-10-29 18:33:24] 	at com.vencillio.core.network.mysql.VoteUpdater.lambda$0(VoteUpdater.java:53)
[2015-10-29 18:33:24] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2015-10-29 18:33:24] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-29 18:33:24] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-29 18:33:24] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-29 18:33:24] 	at java.lang.Thread.run(Unknown Source)
[2015-10-29 19:06:06] java.lang.NullPointerException
[2015-10-29 19:06:06] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2015-10-29 19:06:06] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:115)
[2015-10-29 19:06:06] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 19:06:06] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 19:06:06] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 19:06:06] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 19:06:06] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 19:08:55] java.lang.NumberFormatException: For input string: "6l000"
[2015-10-29 19:08:55] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-29 19:08:55] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 19:08:55] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-29 19:08:55] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-29 19:08:55] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-29 19:08:55] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-29 19:08:55] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-29 19:08:55] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-29 19:08:55] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 19:08:55] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 23:57:28] java.lang.NullPointerException
[2015-10-29 23:57:28] 	at com.vencillio.rs2.content.combat.formula.RangeFormulas.calculateRangeAttack(RangeFormulas.java:78)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.content.combat.impl.Ranged.execute(Ranged.java:41)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:92)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1522)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.entity.World.process(World.java:321)
[2015-10-29 23:57:28] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 23:57:28] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-29 23:57:28] java.lang.NullPointerException
[2015-10-29 23:57:28] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:329)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1448)
[2015-10-29 23:57:28] 	at com.vencillio.rs2.entity.World.process(World.java:332)
[2015-10-29 23:57:28] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-29 23:57:28] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
